config/routes.rb
Rails.application.routes.draw do
  root "groups#index"
  devise_for :users
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :group_name, presence: true, uniqueness: true                                                                                                  
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group                                                                                                  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: "グループを編集しました"
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:group_name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end

  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chats/_main_chat.html.haml
.main
  .main__header
    .main__header__group-info
      .main__header__group-info__name
        グループ名
      .main__header__group-info__member
        member:  フロント太郎
    =link_to "Edit", "#", class:"main__header__edit-btn"   
  .main__body
    .main__body__content
      .main__body__content__info
        .main__body__content__info__name
          ユーザー名
        .main__body__content__info__time
          2020/1/4
      .main__body__content__text     
        おはよう  
    .main__body__content
      .main__body__content__info
        .main__body__content__info__name
          ユーザー名
        .main__body__content__info__time
          2020/1/4
      .main__body__content__text     
        おはよう 

  .main__message-form    
    = form_for("aaa") do |f|
      .main__message-form__content
        = f.text_field :text, class: "main__message-form__content__text-box", placeholder: "type a message"
        = f.label :image, class: "main__message-form__content__image" do
          = icon("fas", "image")
          = f.file_field :image, class: "main__message-form__content__image__btn"
        = f.submit "Send", class: "main__message-form__content__send-btn"

app/views/chats/_side_bar.html.haml
.side-bar
  .side-bar__header
    .side-bar__header__content
      .side-bar__header__content__name
        = current_user.name
      .side-bar__header__content__icon
        = link_to "#" do
          = icon("fas", "edit", class: "side-bar__header__content__icon")
        = link_to edit_user_path(current_user) do
          = icon("fas", "cog", class: "side-bar__header__content__icon")


  .side-bar__body
    .side-bar__body__content 
      .side-bar__body__content__group-name
        グループ名
      .side-bar__body__content__text
        メッセージ

app/views/chats/index.html.haml
.wrapper
  = render "shared/side_bar"
  = render "main_chat"

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :group_name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :group_name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render "form", group: @group

app/views/groups/index.html.haml
= render "shared/side_bar", groups: @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render "form", group: @group

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/shared/_side_bar.html.haml
.side-bar
  .side-bar__header
    .side-bar__header__content
      .side-bar__header__content__name
        = current_user.name
      .side-bar__header__content__icon
        = link_to new_group_path do
          = icon("fas", "edit", class: "side-bar__header__content__icon")
        = link_to edit_user_path(current_user) do
          = icon("fas", "cog", class: "side-bar__header__content__icon")


  .side-bar__body    
    - current_user.groups.each do |group|
      .side-bar__body__content 
        = link_to "#{group.group_name}", root_path, class:"side-bar__body__content__group-name", style:"text-decoration: none"
        .side-bar__body__content__text
          メッセージ

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'